version: "3"

services:
  crontab:
    build: .
    command:
      - "* * * * * ls "
      - "* * * * * bash /app/test.sh"
    volumes:
      - .:/app
      - ./crontab:/etc/crontab
      - /var/run/docker.sock:/var/run/docker.sock
